version: "3"

services:
  api:
    build: ./api
    links:
      - db
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - ENV=local
      - CONIFER_DB_URL=postgresql://postgres@db/conifer

  # Replaced by a dedicated database server in production (e.g. AWS RDS)
  db:
    image: postgres:14.8
    expose:
      - "5432"
    ports:
      # Map to a non-default port to avoid conflicts on localhost
      - "15432:5432"
    environment:
      - POSTGRES_DB=conifer
      - POSTGRES_HOST_AUTH_METHOD=trust
